### ISSUE TITLE
Add 2019 CPS

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/taxdata#346]
Looks like this is blocked by NBER not yet having published their SAS script at http://data.nber.org/data/cps_progs.html. Is that right @andersonfrailey?

**Comment by MaxGhenis** [comment]
Actually I'd bet they don't have SAS scripts because the 2019 files are just CSVs: http://data.nber.org/cps/asecpub19csv.zip

Will this require merging the person/family/household records then? e.g. `ffpos` isn't in the person record.

**Comment by MaxGhenis** [comment]
The Census Bureau [published](https://www.census.gov/data/datasets/time-series/demo/cps/cps-asec.html) the 2019 ASEC as a fixed-width file. They don't have SAS input statements like NBER does (only for the replicate weights), but I tried just applying the taxdata 2018 logic on it using #345, which works correctly for 2018 data. But it looks like the file structure changed:
```
(base) mghenis@penguin:~/PSLmodels/taxdata/cps_data/pycps$ python create.py 
C-TAM imputed benefits are not available for 2018. Creating file with benefits reported in the CPS.
Reading DAT file
Creating Records
2018:   0%|                                                                                                                                                                                                       | 0/354345 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "create.py", line 158, in <module>
    benefits=True, verbose=True
  File "create.py", line 78, in create
    benefits=_benefits, exportpkl=exportpkl, exportcsv=exportcsv
  File "/home/mghenis/PSLmodels/taxdata/cps_data/pycps/cpsmar.py", line 147, in create_cps
    house = parse(record, parsing_dict["household"])
  File "/home/mghenis/PSLmodels/taxdata/cps_data/pycps/cpsmar.py", line 102, in parse
    value = int(rec[start: end])
ValueError: invalid literal for int() with base 10: ''
```

I'll try merging the CSVs instead.
