### ISSUE TITLE
Issue error from report.py

### ISSUE THREAD

**Issue by bodiyang** [PSLmodels/taxdata#423]
Issue error when generating report. 

```
(base) bodiyang@BYang-MBP history % python report.py "421"
Traceback (most recent call last):
  File "/Users/bodiyang/Desktop/taxdata/taxdata/history/report.py", line 432, in <module>
    report()
  File "/Users/bodiyang/Desktop/taxdata/taxdata/history/report.py", line 112, in report
    elm = r.html.find("span.js-issue-title")[0]
IndexError: list index out of range
```

Web scraping parts may need updates in report.py

**Comment by bodiyang** [comment]
to be solved in [PR 421](https://github.com/PSLmodels/taxdata/pull/421)
